package com.ldxy.entity;

public class Canteen {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column canteen_ts_tb.id
	 * @mbg.generated  Tue Apr 23 21:16:59 CST 2019
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column canteen_ts_tb.ts_canteen_number
	 * @mbg.generated  Tue Apr 23 21:16:59 CST 2019
	 */
	private String tsCanteenNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column canteen_ts_tb.ts_tower_number
	 * @mbg.generated  Tue Apr 23 21:16:59 CST 2019
	 */
	private String tsTowerNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column canteen_ts_tb.ts_window_number
	 * @mbg.generated  Tue Apr 23 21:16:59 CST 2019
	 */
	private String tsWindowNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column canteen_ts_tb.ts_reason
	 * @mbg.generated  Tue Apr 23 21:16:59 CST 2019
	 */
	private String tsReason;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column canteen_ts_tb.ts_time
	 * @mbg.generated  Tue Apr 23 21:16:59 CST 2019
	 */
	private String tsTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column canteen_ts_tb.remark
	 * @mbg.generated  Tue Apr 23 21:16:59 CST 2019
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column canteen_ts_tb.id
	 * @return  the value of canteen_ts_tb.id
	 * @mbg.generated  Tue Apr 23 21:16:59 CST 2019
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column canteen_ts_tb.id
	 * @param id  the value for canteen_ts_tb.id
	 * @mbg.generated  Tue Apr 23 21:16:59 CST 2019
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column canteen_ts_tb.ts_canteen_number
	 * @return  the value of canteen_ts_tb.ts_canteen_number
	 * @mbg.generated  Tue Apr 23 21:16:59 CST 2019
	 */
	public String getTsCanteenNumber() {
		return tsCanteenNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column canteen_ts_tb.ts_canteen_number
	 * @param tsCanteenNumber  the value for canteen_ts_tb.ts_canteen_number
	 * @mbg.generated  Tue Apr 23 21:16:59 CST 2019
	 */
	public void setTsCanteenNumber(String tsCanteenNumber) {
		this.tsCanteenNumber = tsCanteenNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column canteen_ts_tb.ts_tower_number
	 * @return  the value of canteen_ts_tb.ts_tower_number
	 * @mbg.generated  Tue Apr 23 21:16:59 CST 2019
	 */
	public String getTsTowerNumber() {
		return tsTowerNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column canteen_ts_tb.ts_tower_number
	 * @param tsTowerNumber  the value for canteen_ts_tb.ts_tower_number
	 * @mbg.generated  Tue Apr 23 21:16:59 CST 2019
	 */
	public void setTsTowerNumber(String tsTowerNumber) {
		this.tsTowerNumber = tsTowerNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column canteen_ts_tb.ts_window_number
	 * @return  the value of canteen_ts_tb.ts_window_number
	 * @mbg.generated  Tue Apr 23 21:16:59 CST 2019
	 */
	public String getTsWindowNumber() {
		return tsWindowNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column canteen_ts_tb.ts_window_number
	 * @param tsWindowNumber  the value for canteen_ts_tb.ts_window_number
	 * @mbg.generated  Tue Apr 23 21:16:59 CST 2019
	 */
	public void setTsWindowNumber(String tsWindowNumber) {
		this.tsWindowNumber = tsWindowNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column canteen_ts_tb.ts_reason
	 * @return  the value of canteen_ts_tb.ts_reason
	 * @mbg.generated  Tue Apr 23 21:16:59 CST 2019
	 */
	public String getTsReason() {
		return tsReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column canteen_ts_tb.ts_reason
	 * @param tsReason  the value for canteen_ts_tb.ts_reason
	 * @mbg.generated  Tue Apr 23 21:16:59 CST 2019
	 */
	public void setTsReason(String tsReason) {
		this.tsReason = tsReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column canteen_ts_tb.ts_time
	 * @return  the value of canteen_ts_tb.ts_time
	 * @mbg.generated  Tue Apr 23 21:16:59 CST 2019
	 */
	public String getTsTime() {
		return tsTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column canteen_ts_tb.ts_time
	 * @param tsTime  the value for canteen_ts_tb.ts_time
	 * @mbg.generated  Tue Apr 23 21:16:59 CST 2019
	 */
	public void setTsTime(String tsTime) {
		this.tsTime = tsTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column canteen_ts_tb.remark
	 * @return  the value of canteen_ts_tb.remark
	 * @mbg.generated  Tue Apr 23 21:16:59 CST 2019
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column canteen_ts_tb.remark
	 * @param remark  the value for canteen_ts_tb.remark
	 * @mbg.generated  Tue Apr 23 21:16:59 CST 2019
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}
}