package com.ldxy.entity;

import java.util.ArrayList;
import java.util.List;

public class IdeaExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table idea_tb
	 * @mbg.generated  Tue Apr 30 20:38:38 CST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table idea_tb
	 * @mbg.generated  Tue Apr 30 20:38:38 CST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table idea_tb
	 * @mbg.generated  Tue Apr 30 20:38:38 CST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table idea_tb
	 * @mbg.generated  Tue Apr 30 20:38:38 CST 2019
	 */
	public IdeaExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table idea_tb
	 * @mbg.generated  Tue Apr 30 20:38:38 CST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table idea_tb
	 * @mbg.generated  Tue Apr 30 20:38:38 CST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table idea_tb
	 * @mbg.generated  Tue Apr 30 20:38:38 CST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table idea_tb
	 * @mbg.generated  Tue Apr 30 20:38:38 CST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table idea_tb
	 * @mbg.generated  Tue Apr 30 20:38:38 CST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table idea_tb
	 * @mbg.generated  Tue Apr 30 20:38:38 CST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table idea_tb
	 * @mbg.generated  Tue Apr 30 20:38:38 CST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table idea_tb
	 * @mbg.generated  Tue Apr 30 20:38:38 CST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table idea_tb
	 * @mbg.generated  Tue Apr 30 20:38:38 CST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table idea_tb
	 * @mbg.generated  Tue Apr 30 20:38:38 CST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table idea_tb
	 * @mbg.generated  Tue Apr 30 20:38:38 CST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andPersonIsNull() {
			addCriterion("person is null");
			return (Criteria) this;
		}

		public Criteria andPersonIsNotNull() {
			addCriterion("person is not null");
			return (Criteria) this;
		}

		public Criteria andPersonEqualTo(String value) {
			addCriterion("person =", value, "person");
			return (Criteria) this;
		}

		public Criteria andPersonNotEqualTo(String value) {
			addCriterion("person <>", value, "person");
			return (Criteria) this;
		}

		public Criteria andPersonGreaterThan(String value) {
			addCriterion("person >", value, "person");
			return (Criteria) this;
		}

		public Criteria andPersonGreaterThanOrEqualTo(String value) {
			addCriterion("person >=", value, "person");
			return (Criteria) this;
		}

		public Criteria andPersonLessThan(String value) {
			addCriterion("person <", value, "person");
			return (Criteria) this;
		}

		public Criteria andPersonLessThanOrEqualTo(String value) {
			addCriterion("person <=", value, "person");
			return (Criteria) this;
		}

		public Criteria andPersonLike(String value) {
			addCriterion("person like", value, "person");
			return (Criteria) this;
		}

		public Criteria andPersonNotLike(String value) {
			addCriterion("person not like", value, "person");
			return (Criteria) this;
		}

		public Criteria andPersonIn(List<String> values) {
			addCriterion("person in", values, "person");
			return (Criteria) this;
		}

		public Criteria andPersonNotIn(List<String> values) {
			addCriterion("person not in", values, "person");
			return (Criteria) this;
		}

		public Criteria andPersonBetween(String value1, String value2) {
			addCriterion("person between", value1, value2, "person");
			return (Criteria) this;
		}

		public Criteria andPersonNotBetween(String value1, String value2) {
			addCriterion("person not between", value1, value2, "person");
			return (Criteria) this;
		}

		public Criteria andTimeIsNull() {
			addCriterion("time is null");
			return (Criteria) this;
		}

		public Criteria andTimeIsNotNull() {
			addCriterion("time is not null");
			return (Criteria) this;
		}

		public Criteria andTimeEqualTo(String value) {
			addCriterion("time =", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeNotEqualTo(String value) {
			addCriterion("time <>", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeGreaterThan(String value) {
			addCriterion("time >", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeGreaterThanOrEqualTo(String value) {
			addCriterion("time >=", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeLessThan(String value) {
			addCriterion("time <", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeLessThanOrEqualTo(String value) {
			addCriterion("time <=", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeLike(String value) {
			addCriterion("time like", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeNotLike(String value) {
			addCriterion("time not like", value, "time");
			return (Criteria) this;
		}

		public Criteria andTimeIn(List<String> values) {
			addCriterion("time in", values, "time");
			return (Criteria) this;
		}

		public Criteria andTimeNotIn(List<String> values) {
			addCriterion("time not in", values, "time");
			return (Criteria) this;
		}

		public Criteria andTimeBetween(String value1, String value2) {
			addCriterion("time between", value1, value2, "time");
			return (Criteria) this;
		}

		public Criteria andTimeNotBetween(String value1, String value2) {
			addCriterion("time not between", value1, value2, "time");
			return (Criteria) this;
		}

		public Criteria andTitleIsNull() {
			addCriterion("title is null");
			return (Criteria) this;
		}

		public Criteria andTitleIsNotNull() {
			addCriterion("title is not null");
			return (Criteria) this;
		}

		public Criteria andTitleEqualTo(String value) {
			addCriterion("title =", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotEqualTo(String value) {
			addCriterion("title <>", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThan(String value) {
			addCriterion("title >", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThanOrEqualTo(String value) {
			addCriterion("title >=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThan(String value) {
			addCriterion("title <", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThanOrEqualTo(String value) {
			addCriterion("title <=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLike(String value) {
			addCriterion("title like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotLike(String value) {
			addCriterion("title not like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleIn(List<String> values) {
			addCriterion("title in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotIn(List<String> values) {
			addCriterion("title not in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleBetween(String value1, String value2) {
			addCriterion("title between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotBetween(String value1, String value2) {
			addCriterion("title not between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andContentIsNull() {
			addCriterion("content is null");
			return (Criteria) this;
		}

		public Criteria andContentIsNotNull() {
			addCriterion("content is not null");
			return (Criteria) this;
		}

		public Criteria andContentEqualTo(String value) {
			addCriterion("content =", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotEqualTo(String value) {
			addCriterion("content <>", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentGreaterThan(String value) {
			addCriterion("content >", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentGreaterThanOrEqualTo(String value) {
			addCriterion("content >=", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLessThan(String value) {
			addCriterion("content <", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLessThanOrEqualTo(String value) {
			addCriterion("content <=", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLike(String value) {
			addCriterion("content like", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotLike(String value) {
			addCriterion("content not like", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentIn(List<String> values) {
			addCriterion("content in", values, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotIn(List<String> values) {
			addCriterion("content not in", values, "content");
			return (Criteria) this;
		}

		public Criteria andContentBetween(String value1, String value2) {
			addCriterion("content between", value1, value2, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotBetween(String value1, String value2) {
			addCriterion("content not between", value1, value2, "content");
			return (Criteria) this;
		}

		public Criteria andClassesIsNull() {
			addCriterion("classes is null");
			return (Criteria) this;
		}

		public Criteria andClassesIsNotNull() {
			addCriterion("classes is not null");
			return (Criteria) this;
		}

		public Criteria andClassesEqualTo(String value) {
			addCriterion("classes =", value, "classes");
			return (Criteria) this;
		}

		public Criteria andClassesNotEqualTo(String value) {
			addCriterion("classes <>", value, "classes");
			return (Criteria) this;
		}

		public Criteria andClassesGreaterThan(String value) {
			addCriterion("classes >", value, "classes");
			return (Criteria) this;
		}

		public Criteria andClassesGreaterThanOrEqualTo(String value) {
			addCriterion("classes >=", value, "classes");
			return (Criteria) this;
		}

		public Criteria andClassesLessThan(String value) {
			addCriterion("classes <", value, "classes");
			return (Criteria) this;
		}

		public Criteria andClassesLessThanOrEqualTo(String value) {
			addCriterion("classes <=", value, "classes");
			return (Criteria) this;
		}

		public Criteria andClassesLike(String value) {
			addCriterion("classes like", value, "classes");
			return (Criteria) this;
		}

		public Criteria andClassesNotLike(String value) {
			addCriterion("classes not like", value, "classes");
			return (Criteria) this;
		}

		public Criteria andClassesIn(List<String> values) {
			addCriterion("classes in", values, "classes");
			return (Criteria) this;
		}

		public Criteria andClassesNotIn(List<String> values) {
			addCriterion("classes not in", values, "classes");
			return (Criteria) this;
		}

		public Criteria andClassesBetween(String value1, String value2) {
			addCriterion("classes between", value1, value2, "classes");
			return (Criteria) this;
		}

		public Criteria andClassesNotBetween(String value1, String value2) {
			addCriterion("classes not between", value1, value2, "classes");
			return (Criteria) this;
		}

		public Criteria andCollageIsNull() {
			addCriterion("collage is null");
			return (Criteria) this;
		}

		public Criteria andCollageIsNotNull() {
			addCriterion("collage is not null");
			return (Criteria) this;
		}

		public Criteria andCollageEqualTo(String value) {
			addCriterion("collage =", value, "collage");
			return (Criteria) this;
		}

		public Criteria andCollageNotEqualTo(String value) {
			addCriterion("collage <>", value, "collage");
			return (Criteria) this;
		}

		public Criteria andCollageGreaterThan(String value) {
			addCriterion("collage >", value, "collage");
			return (Criteria) this;
		}

		public Criteria andCollageGreaterThanOrEqualTo(String value) {
			addCriterion("collage >=", value, "collage");
			return (Criteria) this;
		}

		public Criteria andCollageLessThan(String value) {
			addCriterion("collage <", value, "collage");
			return (Criteria) this;
		}

		public Criteria andCollageLessThanOrEqualTo(String value) {
			addCriterion("collage <=", value, "collage");
			return (Criteria) this;
		}

		public Criteria andCollageLike(String value) {
			addCriterion("collage like", value, "collage");
			return (Criteria) this;
		}

		public Criteria andCollageNotLike(String value) {
			addCriterion("collage not like", value, "collage");
			return (Criteria) this;
		}

		public Criteria andCollageIn(List<String> values) {
			addCriterion("collage in", values, "collage");
			return (Criteria) this;
		}

		public Criteria andCollageNotIn(List<String> values) {
			addCriterion("collage not in", values, "collage");
			return (Criteria) this;
		}

		public Criteria andCollageBetween(String value1, String value2) {
			addCriterion("collage between", value1, value2, "collage");
			return (Criteria) this;
		}

		public Criteria andCollageNotBetween(String value1, String value2) {
			addCriterion("collage not between", value1, value2, "collage");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNull() {
			addCriterion("remark is null");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNotNull() {
			addCriterion("remark is not null");
			return (Criteria) this;
		}

		public Criteria andRemarkEqualTo(String value) {
			addCriterion("remark =", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotEqualTo(String value) {
			addCriterion("remark <>", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThan(String value) {
			addCriterion("remark >", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("remark >=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThan(String value) {
			addCriterion("remark <", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThanOrEqualTo(String value) {
			addCriterion("remark <=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLike(String value) {
			addCriterion("remark like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotLike(String value) {
			addCriterion("remark not like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkIn(List<String> values) {
			addCriterion("remark in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotIn(List<String> values) {
			addCriterion("remark not in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkBetween(String value1, String value2) {
			addCriterion("remark between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotBetween(String value1, String value2) {
			addCriterion("remark not between", value1, value2, "remark");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table idea_tb
	 * @mbg.generated  Tue Apr 30 20:38:38 CST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table idea_tb
     *
     * @mbg.generated do_not_delete_during_merge Tue Apr 30 20:08:13 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}