package com.ldxy.entity;

import java.util.ArrayList;
import java.util.List;

public class LoseFoundExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lose_found_tb
     *
     * @mbg.generated Thu Apr 18 19:35:10 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lose_found_tb
     *
     * @mbg.generated Thu Apr 18 19:35:10 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lose_found_tb
     *
     * @mbg.generated Thu Apr 18 19:35:10 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lose_found_tb
     *
     * @mbg.generated Thu Apr 18 19:35:10 CST 2019
     */
    public LoseFoundExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lose_found_tb
     *
     * @mbg.generated Thu Apr 18 19:35:10 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lose_found_tb
     *
     * @mbg.generated Thu Apr 18 19:35:10 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lose_found_tb
     *
     * @mbg.generated Thu Apr 18 19:35:10 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lose_found_tb
     *
     * @mbg.generated Thu Apr 18 19:35:10 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lose_found_tb
     *
     * @mbg.generated Thu Apr 18 19:35:10 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lose_found_tb
     *
     * @mbg.generated Thu Apr 18 19:35:10 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lose_found_tb
     *
     * @mbg.generated Thu Apr 18 19:35:10 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lose_found_tb
     *
     * @mbg.generated Thu Apr 18 19:35:10 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lose_found_tb
     *
     * @mbg.generated Thu Apr 18 19:35:10 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lose_found_tb
     *
     * @mbg.generated Thu Apr 18 19:35:10 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lose_found_tb
     *
     * @mbg.generated Thu Apr 18 19:35:10 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andLoseNameIsNull() {
            addCriterion("lose_name is null");
            return (Criteria) this;
        }

        public Criteria andLoseNameIsNotNull() {
            addCriterion("lose_name is not null");
            return (Criteria) this;
        }

        public Criteria andLoseNameEqualTo(String value) {
            addCriterion("lose_name =", value, "loseName");
            return (Criteria) this;
        }

        public Criteria andLoseNameNotEqualTo(String value) {
            addCriterion("lose_name <>", value, "loseName");
            return (Criteria) this;
        }

        public Criteria andLoseNameGreaterThan(String value) {
            addCriterion("lose_name >", value, "loseName");
            return (Criteria) this;
        }

        public Criteria andLoseNameGreaterThanOrEqualTo(String value) {
            addCriterion("lose_name >=", value, "loseName");
            return (Criteria) this;
        }

        public Criteria andLoseNameLessThan(String value) {
            addCriterion("lose_name <", value, "loseName");
            return (Criteria) this;
        }

        public Criteria andLoseNameLessThanOrEqualTo(String value) {
            addCriterion("lose_name <=", value, "loseName");
            return (Criteria) this;
        }

        public Criteria andLoseNameLike(String value) {
            addCriterion("lose_name like", value, "loseName");
            return (Criteria) this;
        }

        public Criteria andLoseNameNotLike(String value) {
            addCriterion("lose_name not like", value, "loseName");
            return (Criteria) this;
        }

        public Criteria andLoseNameIn(List<String> values) {
            addCriterion("lose_name in", values, "loseName");
            return (Criteria) this;
        }

        public Criteria andLoseNameNotIn(List<String> values) {
            addCriterion("lose_name not in", values, "loseName");
            return (Criteria) this;
        }

        public Criteria andLoseNameBetween(String value1, String value2) {
            addCriterion("lose_name between", value1, value2, "loseName");
            return (Criteria) this;
        }

        public Criteria andLoseNameNotBetween(String value1, String value2) {
            addCriterion("lose_name not between", value1, value2, "loseName");
            return (Criteria) this;
        }

        public Criteria andLoseTimeIsNull() {
            addCriterion("lose_time is null");
            return (Criteria) this;
        }

        public Criteria andLoseTimeIsNotNull() {
            addCriterion("lose_time is not null");
            return (Criteria) this;
        }

        public Criteria andLoseTimeEqualTo(String value) {
            addCriterion("lose_time =", value, "loseTime");
            return (Criteria) this;
        }

        public Criteria andLoseTimeNotEqualTo(String value) {
            addCriterion("lose_time <>", value, "loseTime");
            return (Criteria) this;
        }

        public Criteria andLoseTimeGreaterThan(String value) {
            addCriterion("lose_time >", value, "loseTime");
            return (Criteria) this;
        }

        public Criteria andLoseTimeGreaterThanOrEqualTo(String value) {
            addCriterion("lose_time >=", value, "loseTime");
            return (Criteria) this;
        }

        public Criteria andLoseTimeLessThan(String value) {
            addCriterion("lose_time <", value, "loseTime");
            return (Criteria) this;
        }

        public Criteria andLoseTimeLessThanOrEqualTo(String value) {
            addCriterion("lose_time <=", value, "loseTime");
            return (Criteria) this;
        }

        public Criteria andLoseTimeLike(String value) {
            addCriterion("lose_time like", value, "loseTime");
            return (Criteria) this;
        }

        public Criteria andLoseTimeNotLike(String value) {
            addCriterion("lose_time not like", value, "loseTime");
            return (Criteria) this;
        }

        public Criteria andLoseTimeIn(List<String> values) {
            addCriterion("lose_time in", values, "loseTime");
            return (Criteria) this;
        }

        public Criteria andLoseTimeNotIn(List<String> values) {
            addCriterion("lose_time not in", values, "loseTime");
            return (Criteria) this;
        }

        public Criteria andLoseTimeBetween(String value1, String value2) {
            addCriterion("lose_time between", value1, value2, "loseTime");
            return (Criteria) this;
        }

        public Criteria andLoseTimeNotBetween(String value1, String value2) {
            addCriterion("lose_time not between", value1, value2, "loseTime");
            return (Criteria) this;
        }

        public Criteria andLoseSjManIsNull() {
            addCriterion("lose_sj_man is null");
            return (Criteria) this;
        }

        public Criteria andLoseSjManIsNotNull() {
            addCriterion("lose_sj_man is not null");
            return (Criteria) this;
        }

        public Criteria andLoseSjManEqualTo(String value) {
            addCriterion("lose_sj_man =", value, "loseSjMan");
            return (Criteria) this;
        }

        public Criteria andLoseSjManNotEqualTo(String value) {
            addCriterion("lose_sj_man <>", value, "loseSjMan");
            return (Criteria) this;
        }

        public Criteria andLoseSjManGreaterThan(String value) {
            addCriterion("lose_sj_man >", value, "loseSjMan");
            return (Criteria) this;
        }

        public Criteria andLoseSjManGreaterThanOrEqualTo(String value) {
            addCriterion("lose_sj_man >=", value, "loseSjMan");
            return (Criteria) this;
        }

        public Criteria andLoseSjManLessThan(String value) {
            addCriterion("lose_sj_man <", value, "loseSjMan");
            return (Criteria) this;
        }

        public Criteria andLoseSjManLessThanOrEqualTo(String value) {
            addCriterion("lose_sj_man <=", value, "loseSjMan");
            return (Criteria) this;
        }

        public Criteria andLoseSjManLike(String value) {
            addCriterion("lose_sj_man like", value, "loseSjMan");
            return (Criteria) this;
        }

        public Criteria andLoseSjManNotLike(String value) {
            addCriterion("lose_sj_man not like", value, "loseSjMan");
            return (Criteria) this;
        }

        public Criteria andLoseSjManIn(List<String> values) {
            addCriterion("lose_sj_man in", values, "loseSjMan");
            return (Criteria) this;
        }

        public Criteria andLoseSjManNotIn(List<String> values) {
            addCriterion("lose_sj_man not in", values, "loseSjMan");
            return (Criteria) this;
        }

        public Criteria andLoseSjManBetween(String value1, String value2) {
            addCriterion("lose_sj_man between", value1, value2, "loseSjMan");
            return (Criteria) this;
        }

        public Criteria andLoseSjManNotBetween(String value1, String value2) {
            addCriterion("lose_sj_man not between", value1, value2, "loseSjMan");
            return (Criteria) this;
        }

        public Criteria andLoseSjPhoneIsNull() {
            addCriterion("lose_sj_phone is null");
            return (Criteria) this;
        }

        public Criteria andLoseSjPhoneIsNotNull() {
            addCriterion("lose_sj_phone is not null");
            return (Criteria) this;
        }

        public Criteria andLoseSjPhoneEqualTo(String value) {
            addCriterion("lose_sj_phone =", value, "loseSjPhone");
            return (Criteria) this;
        }

        public Criteria andLoseSjPhoneNotEqualTo(String value) {
            addCriterion("lose_sj_phone <>", value, "loseSjPhone");
            return (Criteria) this;
        }

        public Criteria andLoseSjPhoneGreaterThan(String value) {
            addCriterion("lose_sj_phone >", value, "loseSjPhone");
            return (Criteria) this;
        }

        public Criteria andLoseSjPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("lose_sj_phone >=", value, "loseSjPhone");
            return (Criteria) this;
        }

        public Criteria andLoseSjPhoneLessThan(String value) {
            addCriterion("lose_sj_phone <", value, "loseSjPhone");
            return (Criteria) this;
        }

        public Criteria andLoseSjPhoneLessThanOrEqualTo(String value) {
            addCriterion("lose_sj_phone <=", value, "loseSjPhone");
            return (Criteria) this;
        }

        public Criteria andLoseSjPhoneLike(String value) {
            addCriterion("lose_sj_phone like", value, "loseSjPhone");
            return (Criteria) this;
        }

        public Criteria andLoseSjPhoneNotLike(String value) {
            addCriterion("lose_sj_phone not like", value, "loseSjPhone");
            return (Criteria) this;
        }

        public Criteria andLoseSjPhoneIn(List<String> values) {
            addCriterion("lose_sj_phone in", values, "loseSjPhone");
            return (Criteria) this;
        }

        public Criteria andLoseSjPhoneNotIn(List<String> values) {
            addCriterion("lose_sj_phone not in", values, "loseSjPhone");
            return (Criteria) this;
        }

        public Criteria andLoseSjPhoneBetween(String value1, String value2) {
            addCriterion("lose_sj_phone between", value1, value2, "loseSjPhone");
            return (Criteria) this;
        }

        public Criteria andLoseSjPhoneNotBetween(String value1, String value2) {
            addCriterion("lose_sj_phone not between", value1, value2, "loseSjPhone");
            return (Criteria) this;
        }

        public Criteria andLoseManIsNull() {
            addCriterion("lose_man is null");
            return (Criteria) this;
        }

        public Criteria andLoseManIsNotNull() {
            addCriterion("lose_man is not null");
            return (Criteria) this;
        }

        public Criteria andLoseManEqualTo(String value) {
            addCriterion("lose_man =", value, "loseMan");
            return (Criteria) this;
        }

        public Criteria andLoseManNotEqualTo(String value) {
            addCriterion("lose_man <>", value, "loseMan");
            return (Criteria) this;
        }

        public Criteria andLoseManGreaterThan(String value) {
            addCriterion("lose_man >", value, "loseMan");
            return (Criteria) this;
        }

        public Criteria andLoseManGreaterThanOrEqualTo(String value) {
            addCriterion("lose_man >=", value, "loseMan");
            return (Criteria) this;
        }

        public Criteria andLoseManLessThan(String value) {
            addCriterion("lose_man <", value, "loseMan");
            return (Criteria) this;
        }

        public Criteria andLoseManLessThanOrEqualTo(String value) {
            addCriterion("lose_man <=", value, "loseMan");
            return (Criteria) this;
        }

        public Criteria andLoseManLike(String value) {
            addCriterion("lose_man like", value, "loseMan");
            return (Criteria) this;
        }

        public Criteria andLoseManNotLike(String value) {
            addCriterion("lose_man not like", value, "loseMan");
            return (Criteria) this;
        }

        public Criteria andLoseManIn(List<String> values) {
            addCriterion("lose_man in", values, "loseMan");
            return (Criteria) this;
        }

        public Criteria andLoseManNotIn(List<String> values) {
            addCriterion("lose_man not in", values, "loseMan");
            return (Criteria) this;
        }

        public Criteria andLoseManBetween(String value1, String value2) {
            addCriterion("lose_man between", value1, value2, "loseMan");
            return (Criteria) this;
        }

        public Criteria andLoseManNotBetween(String value1, String value2) {
            addCriterion("lose_man not between", value1, value2, "loseMan");
            return (Criteria) this;
        }

        public Criteria andLosePhoneIsNull() {
            addCriterion("lose_phone is null");
            return (Criteria) this;
        }

        public Criteria andLosePhoneIsNotNull() {
            addCriterion("lose_phone is not null");
            return (Criteria) this;
        }

        public Criteria andLosePhoneEqualTo(String value) {
            addCriterion("lose_phone =", value, "losePhone");
            return (Criteria) this;
        }

        public Criteria andLosePhoneNotEqualTo(String value) {
            addCriterion("lose_phone <>", value, "losePhone");
            return (Criteria) this;
        }

        public Criteria andLosePhoneGreaterThan(String value) {
            addCriterion("lose_phone >", value, "losePhone");
            return (Criteria) this;
        }

        public Criteria andLosePhoneGreaterThanOrEqualTo(String value) {
            addCriterion("lose_phone >=", value, "losePhone");
            return (Criteria) this;
        }

        public Criteria andLosePhoneLessThan(String value) {
            addCriterion("lose_phone <", value, "losePhone");
            return (Criteria) this;
        }

        public Criteria andLosePhoneLessThanOrEqualTo(String value) {
            addCriterion("lose_phone <=", value, "losePhone");
            return (Criteria) this;
        }

        public Criteria andLosePhoneLike(String value) {
            addCriterion("lose_phone like", value, "losePhone");
            return (Criteria) this;
        }

        public Criteria andLosePhoneNotLike(String value) {
            addCriterion("lose_phone not like", value, "losePhone");
            return (Criteria) this;
        }

        public Criteria andLosePhoneIn(List<String> values) {
            addCriterion("lose_phone in", values, "losePhone");
            return (Criteria) this;
        }

        public Criteria andLosePhoneNotIn(List<String> values) {
            addCriterion("lose_phone not in", values, "losePhone");
            return (Criteria) this;
        }

        public Criteria andLosePhoneBetween(String value1, String value2) {
            addCriterion("lose_phone between", value1, value2, "losePhone");
            return (Criteria) this;
        }

        public Criteria andLosePhoneNotBetween(String value1, String value2) {
            addCriterion("lose_phone not between", value1, value2, "losePhone");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNull() {
            addCriterion("remarks is null");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNotNull() {
            addCriterion("remarks is not null");
            return (Criteria) this;
        }

        public Criteria andRemarksEqualTo(String value) {
            addCriterion("remarks =", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotEqualTo(String value) {
            addCriterion("remarks <>", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThan(String value) {
            addCriterion("remarks >", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThanOrEqualTo(String value) {
            addCriterion("remarks >=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThan(String value) {
            addCriterion("remarks <", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThanOrEqualTo(String value) {
            addCriterion("remarks <=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLike(String value) {
            addCriterion("remarks like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotLike(String value) {
            addCriterion("remarks not like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksIn(List<String> values) {
            addCriterion("remarks in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotIn(List<String> values) {
            addCriterion("remarks not in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksBetween(String value1, String value2) {
            addCriterion("remarks between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotBetween(String value1, String value2) {
            addCriterion("remarks not between", value1, value2, "remarks");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lose_found_tb
     *
     * @mbg.generated do_not_delete_during_merge Thu Apr 18 19:35:10 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table lose_found_tb
     *
     * @mbg.generated Thu Apr 18 19:35:10 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}