package com.ldxy.entity;

import java.util.ArrayList;
import java.util.List;

public class NewExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table new_tb
     *
     * @mbg.generated Thu Apr 18 21:05:01 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table new_tb
     *
     * @mbg.generated Thu Apr 18 21:05:01 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table new_tb
     *
     * @mbg.generated Thu Apr 18 21:05:01 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_tb
     *
     * @mbg.generated Thu Apr 18 21:05:01 CST 2019
     */
    public NewExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_tb
     *
     * @mbg.generated Thu Apr 18 21:05:01 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_tb
     *
     * @mbg.generated Thu Apr 18 21:05:01 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_tb
     *
     * @mbg.generated Thu Apr 18 21:05:01 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_tb
     *
     * @mbg.generated Thu Apr 18 21:05:01 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_tb
     *
     * @mbg.generated Thu Apr 18 21:05:01 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_tb
     *
     * @mbg.generated Thu Apr 18 21:05:01 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_tb
     *
     * @mbg.generated Thu Apr 18 21:05:01 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_tb
     *
     * @mbg.generated Thu Apr 18 21:05:01 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_tb
     *
     * @mbg.generated Thu Apr 18 21:05:01 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_tb
     *
     * @mbg.generated Thu Apr 18 21:05:01 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table new_tb
     *
     * @mbg.generated Thu Apr 18 21:05:01 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNewTitleIsNull() {
            addCriterion("new_title is null");
            return (Criteria) this;
        }

        public Criteria andNewTitleIsNotNull() {
            addCriterion("new_title is not null");
            return (Criteria) this;
        }

        public Criteria andNewTitleEqualTo(String value) {
            addCriterion("new_title =", value, "newTitle");
            return (Criteria) this;
        }

        public Criteria andNewTitleNotEqualTo(String value) {
            addCriterion("new_title <>", value, "newTitle");
            return (Criteria) this;
        }

        public Criteria andNewTitleGreaterThan(String value) {
            addCriterion("new_title >", value, "newTitle");
            return (Criteria) this;
        }

        public Criteria andNewTitleGreaterThanOrEqualTo(String value) {
            addCriterion("new_title >=", value, "newTitle");
            return (Criteria) this;
        }

        public Criteria andNewTitleLessThan(String value) {
            addCriterion("new_title <", value, "newTitle");
            return (Criteria) this;
        }

        public Criteria andNewTitleLessThanOrEqualTo(String value) {
            addCriterion("new_title <=", value, "newTitle");
            return (Criteria) this;
        }

        public Criteria andNewTitleLike(String value) {
            addCriterion("new_title like", value, "newTitle");
            return (Criteria) this;
        }

        public Criteria andNewTitleNotLike(String value) {
            addCriterion("new_title not like", value, "newTitle");
            return (Criteria) this;
        }

        public Criteria andNewTitleIn(List<String> values) {
            addCriterion("new_title in", values, "newTitle");
            return (Criteria) this;
        }

        public Criteria andNewTitleNotIn(List<String> values) {
            addCriterion("new_title not in", values, "newTitle");
            return (Criteria) this;
        }

        public Criteria andNewTitleBetween(String value1, String value2) {
            addCriterion("new_title between", value1, value2, "newTitle");
            return (Criteria) this;
        }

        public Criteria andNewTitleNotBetween(String value1, String value2) {
            addCriterion("new_title not between", value1, value2, "newTitle");
            return (Criteria) this;
        }

        public Criteria andNewTypeIsNull() {
            addCriterion("new_type is null");
            return (Criteria) this;
        }

        public Criteria andNewTypeIsNotNull() {
            addCriterion("new_type is not null");
            return (Criteria) this;
        }

        public Criteria andNewTypeEqualTo(String value) {
            addCriterion("new_type =", value, "newType");
            return (Criteria) this;
        }

        public Criteria andNewTypeNotEqualTo(String value) {
            addCriterion("new_type <>", value, "newType");
            return (Criteria) this;
        }

        public Criteria andNewTypeGreaterThan(String value) {
            addCriterion("new_type >", value, "newType");
            return (Criteria) this;
        }

        public Criteria andNewTypeGreaterThanOrEqualTo(String value) {
            addCriterion("new_type >=", value, "newType");
            return (Criteria) this;
        }

        public Criteria andNewTypeLessThan(String value) {
            addCriterion("new_type <", value, "newType");
            return (Criteria) this;
        }

        public Criteria andNewTypeLessThanOrEqualTo(String value) {
            addCriterion("new_type <=", value, "newType");
            return (Criteria) this;
        }

        public Criteria andNewTypeLike(String value) {
            addCriterion("new_type like", value, "newType");
            return (Criteria) this;
        }

        public Criteria andNewTypeNotLike(String value) {
            addCriterion("new_type not like", value, "newType");
            return (Criteria) this;
        }

        public Criteria andNewTypeIn(List<String> values) {
            addCriterion("new_type in", values, "newType");
            return (Criteria) this;
        }

        public Criteria andNewTypeNotIn(List<String> values) {
            addCriterion("new_type not in", values, "newType");
            return (Criteria) this;
        }

        public Criteria andNewTypeBetween(String value1, String value2) {
            addCriterion("new_type between", value1, value2, "newType");
            return (Criteria) this;
        }

        public Criteria andNewTypeNotBetween(String value1, String value2) {
            addCriterion("new_type not between", value1, value2, "newType");
            return (Criteria) this;
        }

        public Criteria andNewJjIsNull() {
            addCriterion("new_jj is null");
            return (Criteria) this;
        }

        public Criteria andNewJjIsNotNull() {
            addCriterion("new_jj is not null");
            return (Criteria) this;
        }

        public Criteria andNewJjEqualTo(String value) {
            addCriterion("new_jj =", value, "newJj");
            return (Criteria) this;
        }

        public Criteria andNewJjNotEqualTo(String value) {
            addCriterion("new_jj <>", value, "newJj");
            return (Criteria) this;
        }

        public Criteria andNewJjGreaterThan(String value) {
            addCriterion("new_jj >", value, "newJj");
            return (Criteria) this;
        }

        public Criteria andNewJjGreaterThanOrEqualTo(String value) {
            addCriterion("new_jj >=", value, "newJj");
            return (Criteria) this;
        }

        public Criteria andNewJjLessThan(String value) {
            addCriterion("new_jj <", value, "newJj");
            return (Criteria) this;
        }

        public Criteria andNewJjLessThanOrEqualTo(String value) {
            addCriterion("new_jj <=", value, "newJj");
            return (Criteria) this;
        }

        public Criteria andNewJjLike(String value) {
            addCriterion("new_jj like", value, "newJj");
            return (Criteria) this;
        }

        public Criteria andNewJjNotLike(String value) {
            addCriterion("new_jj not like", value, "newJj");
            return (Criteria) this;
        }

        public Criteria andNewJjIn(List<String> values) {
            addCriterion("new_jj in", values, "newJj");
            return (Criteria) this;
        }

        public Criteria andNewJjNotIn(List<String> values) {
            addCriterion("new_jj not in", values, "newJj");
            return (Criteria) this;
        }

        public Criteria andNewJjBetween(String value1, String value2) {
            addCriterion("new_jj between", value1, value2, "newJj");
            return (Criteria) this;
        }

        public Criteria andNewJjNotBetween(String value1, String value2) {
            addCriterion("new_jj not between", value1, value2, "newJj");
            return (Criteria) this;
        }

        public Criteria andNewAuthorIsNull() {
            addCriterion("new_author is null");
            return (Criteria) this;
        }

        public Criteria andNewAuthorIsNotNull() {
            addCriterion("new_author is not null");
            return (Criteria) this;
        }

        public Criteria andNewAuthorEqualTo(String value) {
            addCriterion("new_author =", value, "newAuthor");
            return (Criteria) this;
        }

        public Criteria andNewAuthorNotEqualTo(String value) {
            addCriterion("new_author <>", value, "newAuthor");
            return (Criteria) this;
        }

        public Criteria andNewAuthorGreaterThan(String value) {
            addCriterion("new_author >", value, "newAuthor");
            return (Criteria) this;
        }

        public Criteria andNewAuthorGreaterThanOrEqualTo(String value) {
            addCriterion("new_author >=", value, "newAuthor");
            return (Criteria) this;
        }

        public Criteria andNewAuthorLessThan(String value) {
            addCriterion("new_author <", value, "newAuthor");
            return (Criteria) this;
        }

        public Criteria andNewAuthorLessThanOrEqualTo(String value) {
            addCriterion("new_author <=", value, "newAuthor");
            return (Criteria) this;
        }

        public Criteria andNewAuthorLike(String value) {
            addCriterion("new_author like", value, "newAuthor");
            return (Criteria) this;
        }

        public Criteria andNewAuthorNotLike(String value) {
            addCriterion("new_author not like", value, "newAuthor");
            return (Criteria) this;
        }

        public Criteria andNewAuthorIn(List<String> values) {
            addCriterion("new_author in", values, "newAuthor");
            return (Criteria) this;
        }

        public Criteria andNewAuthorNotIn(List<String> values) {
            addCriterion("new_author not in", values, "newAuthor");
            return (Criteria) this;
        }

        public Criteria andNewAuthorBetween(String value1, String value2) {
            addCriterion("new_author between", value1, value2, "newAuthor");
            return (Criteria) this;
        }

        public Criteria andNewAuthorNotBetween(String value1, String value2) {
            addCriterion("new_author not between", value1, value2, "newAuthor");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNull() {
            addCriterion("remarks is null");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNotNull() {
            addCriterion("remarks is not null");
            return (Criteria) this;
        }

        public Criteria andRemarksEqualTo(String value) {
            addCriterion("remarks =", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotEqualTo(String value) {
            addCriterion("remarks <>", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThan(String value) {
            addCriterion("remarks >", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThanOrEqualTo(String value) {
            addCriterion("remarks >=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThan(String value) {
            addCriterion("remarks <", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThanOrEqualTo(String value) {
            addCriterion("remarks <=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLike(String value) {
            addCriterion("remarks like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotLike(String value) {
            addCriterion("remarks not like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksIn(List<String> values) {
            addCriterion("remarks in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotIn(List<String> values) {
            addCriterion("remarks not in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksBetween(String value1, String value2) {
            addCriterion("remarks between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotBetween(String value1, String value2) {
            addCriterion("remarks not between", value1, value2, "remarks");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table new_tb
     *
     * @mbg.generated do_not_delete_during_merge Thu Apr 18 21:05:01 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table new_tb
     *
     * @mbg.generated Thu Apr 18 21:05:01 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}