package com.ldxy.dao;

import com.ldxy.entity.Canteen;
import com.ldxy.entity.CanteenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CanteenMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table canteen_ts_tb
	 * @mbg.generated  Tue Apr 23 21:16:59 CST 2019
	 */
	long countByExample(CanteenExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table canteen_ts_tb
	 * @mbg.generated  Tue Apr 23 21:16:59 CST 2019
	 */
	int deleteByExample(CanteenExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table canteen_ts_tb
	 * @mbg.generated  Tue Apr 23 21:16:59 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table canteen_ts_tb
	 * @mbg.generated  Tue Apr 23 21:16:59 CST 2019
	 */
	int insert(Canteen record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table canteen_ts_tb
	 * @mbg.generated  Tue Apr 23 21:16:59 CST 2019
	 */
	int insertSelective(Canteen record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table canteen_ts_tb
	 * @mbg.generated  Tue Apr 23 21:16:59 CST 2019
	 */
	List<Canteen> selectByExample(CanteenExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table canteen_ts_tb
	 * @mbg.generated  Tue Apr 23 21:16:59 CST 2019
	 */
	Canteen selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table canteen_ts_tb
	 * @mbg.generated  Tue Apr 23 21:16:59 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Canteen record, @Param("example") CanteenExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table canteen_ts_tb
	 * @mbg.generated  Tue Apr 23 21:16:59 CST 2019
	 */
	int updateByExample(@Param("record") Canteen record, @Param("example") CanteenExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table canteen_ts_tb
	 * @mbg.generated  Tue Apr 23 21:16:59 CST 2019
	 */
	int updateByPrimaryKeySelective(Canteen record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table canteen_ts_tb
	 * @mbg.generated  Tue Apr 23 21:16:59 CST 2019
	 */
	int updateByPrimaryKey(Canteen record);
}