package com.ldxy.dao;

import com.ldxy.entity.Classes;
import com.ldxy.entity.ClassesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClassesMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table class_tb
	 * @mbg.generated  Mon Apr 22 23:31:21 CST 2019
	 */
	long countByExample(ClassesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table class_tb
	 * @mbg.generated  Mon Apr 22 23:31:21 CST 2019
	 */
	int deleteByExample(ClassesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table class_tb
	 * @mbg.generated  Mon Apr 22 23:31:21 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table class_tb
	 * @mbg.generated  Mon Apr 22 23:31:21 CST 2019
	 */
	int insert(Classes record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table class_tb
	 * @mbg.generated  Mon Apr 22 23:31:21 CST 2019
	 */
	int insertSelective(Classes record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table class_tb
	 * @mbg.generated  Mon Apr 22 23:31:21 CST 2019
	 */
	List<Classes> selectByExample(ClassesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table class_tb
	 * @mbg.generated  Mon Apr 22 23:31:21 CST 2019
	 */
	Classes selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table class_tb
	 * @mbg.generated  Mon Apr 22 23:31:21 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Classes record, @Param("example") ClassesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table class_tb
	 * @mbg.generated  Mon Apr 22 23:31:21 CST 2019
	 */
	int updateByExample(@Param("record") Classes record, @Param("example") ClassesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table class_tb
	 * @mbg.generated  Mon Apr 22 23:31:21 CST 2019
	 */
	int updateByPrimaryKeySelective(Classes record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table class_tb
	 * @mbg.generated  Mon Apr 22 23:31:21 CST 2019
	 */
	int updateByPrimaryKey(Classes record);
}