package com.ldxy.dao;

import com.ldxy.entity.Idea;
import com.ldxy.entity.IdeaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IdeaMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table idea_tb
	 * @mbg.generated  Tue Apr 30 20:38:38 CST 2019
	 */
	long countByExample(IdeaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table idea_tb
	 * @mbg.generated  Tue Apr 30 20:38:38 CST 2019
	 */
	int deleteByExample(IdeaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table idea_tb
	 * @mbg.generated  Tue Apr 30 20:38:38 CST 2019
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table idea_tb
	 * @mbg.generated  Tue Apr 30 20:38:38 CST 2019
	 */
	int insert(Idea record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table idea_tb
	 * @mbg.generated  Tue Apr 30 20:38:38 CST 2019
	 */
	int insertSelective(Idea record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table idea_tb
	 * @mbg.generated  Tue Apr 30 20:38:38 CST 2019
	 */
	List<Idea> selectByExample(IdeaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table idea_tb
	 * @mbg.generated  Tue Apr 30 20:38:38 CST 2019
	 */
	Idea selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table idea_tb
	 * @mbg.generated  Tue Apr 30 20:38:38 CST 2019
	 */
	int updateByExampleSelective(@Param("record") Idea record, @Param("example") IdeaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table idea_tb
	 * @mbg.generated  Tue Apr 30 20:38:38 CST 2019
	 */
	int updateByExample(@Param("record") Idea record, @Param("example") IdeaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table idea_tb
	 * @mbg.generated  Tue Apr 30 20:38:38 CST 2019
	 */
	int updateByPrimaryKeySelective(Idea record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table idea_tb
	 * @mbg.generated  Tue Apr 30 20:38:38 CST 2019
	 */
	int updateByPrimaryKey(Idea record);
}