package com.ldxy.dao;

import com.ldxy.entity.LoseFound;
import com.ldxy.entity.LoseFoundExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LoseFoundMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lose_found_tb
     *
     * @mbg.generated Thu Apr 18 19:35:10 CST 2019
     */
    long countByExample(LoseFoundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lose_found_tb
     *
     * @mbg.generated Thu Apr 18 19:35:10 CST 2019
     */
    int deleteByExample(LoseFoundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lose_found_tb
     *
     * @mbg.generated Thu Apr 18 19:35:10 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lose_found_tb
     *
     * @mbg.generated Thu Apr 18 19:35:10 CST 2019
     */
    int insert(LoseFound record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lose_found_tb
     *
     * @mbg.generated Thu Apr 18 19:35:10 CST 2019
     */
    int insertSelective(LoseFound record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lose_found_tb
     *
     * @mbg.generated Thu Apr 18 19:35:10 CST 2019
     */
    List<LoseFound> selectByExample(LoseFoundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lose_found_tb
     *
     * @mbg.generated Thu Apr 18 19:35:10 CST 2019
     */
    LoseFound selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lose_found_tb
     *
     * @mbg.generated Thu Apr 18 19:35:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") LoseFound record, @Param("example") LoseFoundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lose_found_tb
     *
     * @mbg.generated Thu Apr 18 19:35:10 CST 2019
     */
    int updateByExample(@Param("record") LoseFound record, @Param("example") LoseFoundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lose_found_tb
     *
     * @mbg.generated Thu Apr 18 19:35:10 CST 2019
     */
    int updateByPrimaryKeySelective(LoseFound record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lose_found_tb
     *
     * @mbg.generated Thu Apr 18 19:35:10 CST 2019
     */
    int updateByPrimaryKey(LoseFound record);
}