package com.ldxy.dao;

import com.ldxy.entity.New;
import com.ldxy.entity.NewExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_tb
     *
     * @mbg.generated Thu Apr 18 21:05:01 CST 2019
     */
    long countByExample(NewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_tb
     *
     * @mbg.generated Thu Apr 18 21:05:01 CST 2019
     */
    int deleteByExample(NewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_tb
     *
     * @mbg.generated Thu Apr 18 21:05:01 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_tb
     *
     * @mbg.generated Thu Apr 18 21:05:01 CST 2019
     */
    int insert(New record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_tb
     *
     * @mbg.generated Thu Apr 18 21:05:01 CST 2019
     */
    int insertSelective(New record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_tb
     *
     * @mbg.generated Thu Apr 18 21:05:01 CST 2019
     */
    List<New> selectByExample(NewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_tb
     *
     * @mbg.generated Thu Apr 18 21:05:01 CST 2019
     */
    New selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_tb
     *
     * @mbg.generated Thu Apr 18 21:05:01 CST 2019
     */
    int updateByExampleSelective(@Param("record") New record, @Param("example") NewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_tb
     *
     * @mbg.generated Thu Apr 18 21:05:01 CST 2019
     */
    int updateByExample(@Param("record") New record, @Param("example") NewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_tb
     *
     * @mbg.generated Thu Apr 18 21:05:01 CST 2019
     */
    int updateByPrimaryKeySelective(New record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table new_tb
     *
     * @mbg.generated Thu Apr 18 21:05:01 CST 2019
     */
    int updateByPrimaryKey(New record);
}